In [1]:
print("E-Commerce Data Analyst Project Started!")

E-Commerce Data Analyst Project Started!

In [2]:
import pandas as pd

In [3]:
pd

In [4]:
df = pd.read_csv("../Data/realistic_e_commerce_sales_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../Data/realistic_e_commerce_sales_data.csv'

In [5]:
df = pd.read_csv(
    r"C:\Users\asus\OneDrive\Documents\Ecommerce-Sales-Analytics\Data\realistic_e_commerce_sales_data.csv"
)

In [6]:
df.head()

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,North,NaN,Monitor,Electronics,300.0,5,1500,13.31,Returned,12/8/2023
1,CUST0046,Male,West,22.0,Headphones,Accessories,100.0,2,200,6.93,In Transit,4/9/2023
2,CUST0169,Female,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,8/28/2023
3,CUST0002,Male,North,23.0,Headphones,Accessories,100.0,5,500,12.22,Delivered,1/18/2023
4,CUST0173,Female,South,NaN,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,1/19/2023

In [7]:
df.shape

(1000, 12)

In [8]:
df.columns

Index(['Customer ID', 'Gender', 'Region', 'Age', 'Product Name', 'Category',
       'Unit Price', 'Quantity', 'Total Price', 'Shipping Fee',
       'Shipping Status', 'Order Date'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer ID      1000 non-null   str
 1   Gender           1000 non-null   str
 2   Region           950 non-null    str
 3   Age              900 non-null    float64
 4   Product Name     1000 non-null   str
 5   Category         1000 non-null   str
 6   Unit Price       1000 non-null   float64
 7   Quantity         1000 non-null   int64
 8   Total Price      1000 non-null   int64
 9   Shipping Fee     1000 non-null   float64
 10  Shipping Status  950 non-null    str
 11  Order Date       1000 non-null   str
dtypes: float64(3), int64(2), str(7)
memory usage: 93.9 KB

In [10]:
df.isnull().sum()

Customer ID          0
Gender               0
Region              50
Age                100
Product Name         0
Category             0
Unit Price           0
Quantity             0
Total Price          0
Shipping Fee         0
Shipping Status     50
Order Date           0
dtype: int64

In [11]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

Customer ID         0.0
Gender              0.0
Region              5.0
Age                10.0
Product Name        0.0
Category            0.0
Unit Price          0.0
Quantity            0.0
Total Price         0.0
Shipping Fee        0.0
Shipping Status     5.0
Order Date          0.0
dtype: float64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
print("Gender:")
print(df["Gender"].unique())

print("\nRegion:")
print(df["Region"].unique())

print("\nCategory:")
print(df["Category"].unique())

print("\nProduct Name:")
print(df["Product Name"].unique())

print("\nShipping Status:")
print(df["Shipping Status"].unique())

Gender:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Region:
<StringArray>
['North', 'West', 'South', 'East', nan]
Length: 5, dtype: str

Category:
<StringArray>
['Electronics', 'Accessories', 'Wearables']
Length: 3, dtype: str

Product Name:
<StringArray>
[   'Monitor', 'Headphones',     'Laptop', 'Smartwatch',   'Keyboard',
      'Mouse', 'Smartphone']
Length: 7, dtype: str

Shipping Status:
<StringArray>
['Returned', 'In Transit', 'Delivered', nan]
Length: 4, dtype: str

In [14]:
df["Gender"].value_counts()

Gender
Male      524
Female    476
Name: count, dtype: int64

In [15]:
df["Region"].value_counts(dropna=False)

Region
West     246
South    244
East     231
North    229
NaN       50
Name: count, dtype: int64

In [16]:
df["Category"].value_counts()

Category
Electronics    477
Accessories    401
Wearables      122
Name: count, dtype: int64

In [17]:
df["Product Name"].value_counts()

Product Name
Monitor       181
Laptop        154
Keyboard      145
Smartphone    142
Mouse         136
Smartwatch    122
Headphones    120
Name: count, dtype: int64

In [18]:
df["Shipping Status"].value_counts(dropna=False)

Shipping Status
In Transit    329
Delivered     313
Returned      308
NaN            50
Name: count, dtype: int64

In [19]:
df[["Age", "Unit Price", "Quantity", "Total Price", "Shipping Fee"]].describe()

              Age   Unit Price     Quantity  Total Price  Shipping Fee
count  900.000000  1000.000000  1000.000000  1000.000000   1000.000000
mean    46.695556   457.703777     3.008000  1346.600000     12.416390
std     15.011400   537.231434     1.404246  1834.037877      4.412185
min     18.000000    30.000000     1.000000    30.000000      5.000000
25%     35.000000    50.000000     2.000000   200.000000      8.560000
50%     49.000000   200.000000     3.000000   600.000000     12.315000
75%     59.000000   800.000000     4.000000  1500.000000     16.075000
max     69.000000  3109.560612     5.000000  7500.000000     19.980000

In [20]:
df["Order Date"].min(), df["Order Date"].max()

('1/1/2023', '9/9/2023')

In [21]:
df["Order Date"].sort_values().tail(10)

585    9/4/2023
289    9/4/2023
32     9/5/2023
736    9/6/2023
649    9/6/2023
661    9/6/2023
609    9/6/2023
292    9/8/2023
758    9/9/2023
512    9/9/2023
Name: Order Date, dtype: str

In [22]:
df["Calculated Total"] = df["Unit Price"] * df["Quantity"]

In [23]:
df["Difference"] = df["Total Price"] - df["Calculated Total"]

In [24]:
df["Difference"].value_counts()

Difference
 0.000000       980
-214.608082       3
-1716.864654      2
-64.382424        2
-1609.560612      2
-965.736368       2
-32.191212        1
-107.304041       1
-2575.296981      1
-8047.803060      1
-1609.560612      1
-3219.121224      1
-160.956061       1
-643.824245       1
-6438.242448      1
Name: count, dtype: int64

In [25]:
df["Difference"].value_counts()

Difference
 0.000000       980
-214.608082       3
-1716.864654      2
-64.382424        2
-1609.560612      2
-965.736368       2
-32.191212        1
-107.304041       1
-2575.296981      1
-8047.803060      1
-1609.560612      1
-3219.121224      1
-160.956061       1
-643.824245       1
-6438.242448      1
Name: count, dtype: int64

In [26]:
df[df["Difference"] != 0]

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date,Calculated Total,Difference
26,CUST0264,Male,East,59.0,Smartphone,Electronics,1658.432327,2,1600,11.59,In Transit,2/1/2023,3316.864654,-1716.864654
83,CUST0219,Male,NaN,48.0,Mouse,Accessories,62.191212,2,60,7.40,Returned,8/20/2023,124.382424,-64.382424
84,CUST0037,Male,West,51.0,Keyboard,Accessories,103.652020,4,200,11.41,Returned,5/20/2023,414.608082,-214.608082
110,CUST0223,Female,NaN,20.0,Mouse,Accessories,62.191212,2,60,15.12,In Transit,5/26/2023,124.382424,-64.382424
194,CUST0269,Male,North,64.0,Monitor,Electronics,621.912123,5,1500,6.93,Delivered,4/23/2023,3109.560612,-1609.560612
209,CUST0134,Male,North,NaN,Monitor,Electronics,621.912123,5,1500,7.22,Returned,8/5/2023,3109.560612,-1609.560612
215,CUST0194,Female,West,61.0,Mouse,Accessories,62.191212,1,30,10.41,Returned,1/28/2023,62.191212,-32.191212
226,CUST0264,Female,West,59.0,Keyboard,Accessories,103.652020,4,200,10.49,Delivered,8/21/2023,414.608082,-214.608082
244,CUST0128,Female,North,52.0,Monitor,Electronics,621.912123,3,900,11.04,Delivered,10/25/2023,1865.736368,-965.736368
339,CUST0219,Female,South,48.0,Headphones,Accessories,207.304041,1,100,9.55,Delivered,1/23/2023,207.304041,-107.304041
374,CUST0178,Female,South,44.0,Smartphone,Electronics,1658.432327,3,2400,19.31,Delivered,6/3/2023,4975.296981,-2575.296981
421,CUST0011,Female,West,54.0,Smartphone,Electronics,1658.432327,2,1600,15.80,In Transit,4/6/2023,3316.864654,-1716.864654
511,CUST0047,Male,East,41.0,Headphones,Accessories,207.304041,2,200,9.15,Returned,4/23/2023,414.608082,-214.608082
560,CUST0204,Male,West,54.0,Laptop,Electronics,3109.560612,5,7500,19.71,Returned,4/18/2023,15547.803060,-8047.803060
702,CUST0064,Male,West,61.0,Laptop,Electronics,3109.560612,1,1500,18.37,In Transit,9/1/2023,3109.560612,-1609.560612
756,CUST0138,Female,West,46.0,Laptop,Electronics,3109.560612,2,3000,6.44,Delivered,12/8/2023,6219.121224,-3219.121224
846,CUST0150,Male,West,63.0,Mouse,Accessories,62.191212,5,150,10.81,Delivered,7/1/2023,310.956061,-160.956061
877,CUST0238,Male,East,26.0,Monitor,Electronics,621.912123,2,600,7.02,In Transit,1/3/2024,1243.824245,-643.824245
883,CUST0077,Female,North,NaN,Monitor,Electronics,621.912123,3,900,14.86,In Transit,4/27/2023,1865.736368,-965.736368
967,CUST0131,Female,North,67.0,Laptop,Electronics,3109.560612,4,6000,18.27,NaN,8/26/2023,12438.242448,-6438.242448

In [27]:
(df["Difference"] != 0).sum()

np.int64(20)

In [28]:
error_percentage = (
    (df["Difference"] != 0).sum()
    / len(df)
) * 100

error_percentage

np.float64(2.0)

In [29]:
(df["Unit Price"] < 0).sum()

np.int64(0)

In [30]:
(df["Quantity"] <= 0).sum()

np.int64(0)

In [31]:
(df["Total Price"] < 0).sum()

np.int64(0)

In [32]:
(df["Shipping Fee"] < 0).sum()

np.int64(0)

In [33]:
df["Age"].min(), df["Age"].max()

(np.float64(18.0), np.float64(69.0))

In [34]:
df[(df["Age"] < 18) | (df["Age"] > 100)]

Empty DataFrame
Columns: [Customer ID, Gender, Region, Age, Product Name, Category, Unit Price, Quantity, Total Price, Shipping Fee, Shipping Status, Order Date, Calculated Total, Difference]
Index: []

In [35]:
df["Customer ID"].str.startswith("CUST").value_counts()

Customer ID
True    1000
Name: count, dtype: int64

In [36]:
df["Customer ID"].nunique()

292

In [37]:
for col in ["Gender", "Region", "Product Name",
            "Category", "Shipping Status"]:
    print(col, df[col].dropna().str.strip().unique())

Gender <StringArray>
['Male', 'Female']
Length: 2, dtype: str
Region <StringArray>
['North', 'West', 'South', 'East']
Length: 4, dtype: str
Product Name <StringArray>
[   'Monitor', 'Headphones',     'Laptop', 'Smartwatch',   'Keyboard',
      'Mouse', 'Smartphone']
Length: 7, dtype: str
Category <StringArray>
['Electronics', 'Accessories', 'Wearables']
Length: 3, dtype: str
Shipping Status <StringArray>
['Returned', 'In Transit', 'Delivered']
Length: 3, dtype: str

In [38]:
data_quality = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing %": df.isnull().mean() * 100,
    "Unique Values": df.nunique()
})

data_quality

                  Missing Values  Missing %  Unique Values
Customer ID                    0        0.0            292
Gender                         0        0.0              2
Region                        50        5.0              4
Age                          100       10.0             52
Product Name                   0        0.0              7
Category                       0        0.0              3
Unit Price                     0        0.0             13
Quantity                       0        0.0              5
Total Price                    0        0.0             26
Shipping Fee                   0        0.0            730
Shipping Status               50        5.0              3
Order Date                     0        0.0            340
Calculated Total               0        0.0             40
Difference                     0        0.0             15

In [39]:
df["Difference"].value_counts()

Difference
 0.000000       980
-214.608082       3
-1716.864654      2
-64.382424        2
-1609.560612      2
-965.736368       2
-32.191212        1
-107.304041       1
-2575.296981      1
-8047.803060      1
-1609.560612      1
-3219.121224      1
-160.956061       1
-643.824245       1
-6438.242448      1
Name: count, dtype: int64

In [40]:
(df["Difference"] != 0).sum()

np.int64(20)

In [41]:
error_percentage = (
    (df["Difference"] != 0).sum() / len(df)
) * 100

error_percentage

np.float64(2.0)